name: 'Lint Project'
description: 'Install dependencies, and lint'

inputs:
  working-directory:
    description: 'The directory of the app'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: ./.github/actions/cached-deps
      with:
        working-directory: ${{ inputs.working-directory }}
        caching: 'false'

    - name: Lint code
      run: npm run lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash
