name: Reusable Deploy

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory of the app'
        required: true
        type: string
      artifact-name:
        description: 'Name of the downloaded artifact'
        required: true
        type: string
      script-file:
        description: 'Built JS asset filename (relative to dist)'
        required: true
        type: string
    outputs:
      result-js:
        description: 'Result of the JS deploy action'
        value: ${{ jobs.deploy-js.outputs.outcome }}
      result-docker:
        description: 'Result of the Docker deploy action'
        value: ${{ jobs.deploy-docker.outputs.outcome }}
    secrets:
      dummy-secret:
        required: false
        description: "Dummy secret for testing purposes"

jobs:
  deploy-js:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/dist

      - name: Verify artifact contents
        run: |
          echo "Artifact contents:"
          ls -R dist
        working-directory: ${{ inputs.working-directory }}

      - name: Deploy site (JS Action)
        uses: ./.github/actions/deploy-s3-javascript
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: 'some-bucket'
          dist-folder: ${{ inputs.working-directory }}/dist
          bucket-region: 'us-east-1'

      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> "$GITHUB_OUTPUT"

  deploy-docker:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/dist

      - name: Verify artifact contents
        run: |
          echo "Artifact contents:"
          ls -R dist
        working-directory: ${{ inputs.working-directory }}

      - name: Deploy site (Docker Action)
        uses: ./.github/actions/deploy-s3-docker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: 'some-bucket'
          dist-folder: ${{ inputs.working-directory }}/dist
          bucket-region: 'us-east-1'

      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> "$GITHUB_OUTPUT"