name: Starting Project WITH ENV APP CI Trigger

env:
  APP_DIR: './starting-project-with-env'
  ARTIFACT_NAME: 'dist-files-starting-project-with-env'
#  MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
  MONGODB_CLUSTER_ADDRESS: mongo-db
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  PORT: 8080

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'starting-project-with-env/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    services:
      mongo-db:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Run Test Action
        uses: ./starting-project-with-env/.github/actions/test
        with:
          working-directory: ${{ env.APP_DIR }}
          port: ${{ env.PORT }}

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.build.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Run Build Action
        id: build
        uses: ./starting-project-with-env/.github/actions/build
        with:
          working-directory: ${{ env.APP_DIR }}
          artifact-name: ${{ env.ARTIFACT_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Run Deploy Action
        uses: ./starting-project-with-env/.github/actions/deploy
        with:
          working-directory: ${{ env.APP_DIR }}
          artifact-name: ${{ env.ARTIFACT_NAME }}
          script-file: ${{ needs.build.outputs.script-file }}

