name: Start APP CI Trigger

on:
  push:
    paths:
      - 'start/**'
  workflow_dispatch:

jobs:
  lint-project:

    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Run React lint
        uses: ./start/.github/actions/lint-project


  test-project:
    needs: lint-project
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Run React tests
        uses: ./start/.github/actions/test-project

  deploy-project:
    needs: test-project
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Run dummy deploy
        uses: ./start/.github/actions/deploy
