name: Starting Project APP Conditional CI Trigger

on:
  push:
    branches:
      - main
    paths:
      - 'starting-project-conditional/**'
      - './.github/actions/deploy-s3-javascript'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      app-dir: './starting-project-conditional'
      artifact-name: 'dist-files-starting-project-conditional'
    steps:
      - name: Set shared variables
        run: echo "Exporting shared config"

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Run Lint Action
        uses: ./starting-project-conditional/.github/actions/lint
        with:
          working-directory: ${{ needs.setup.outputs.app-dir }}

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Run Test Action
        uses: ./starting-project-conditional/.github/actions/test
        with:
          working-directory: ${{ needs.setup.outputs.app-dir }}

  build:
    needs: [setup, test]
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.build.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Run Build Action
        id: build
        uses: ./starting-project-conditional/.github/actions/build
        with:
          working-directory: ${{ needs.setup.outputs.app-dir }}
          artifact-name: ${{ needs.setup.outputs.artifact-name }}

  deploy:
    needs: [setup, build]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      working-directory: ${{ needs.setup.outputs.app-dir }}
      artifact-name: ${{ needs.setup.outputs.artifact-name }}
      script-file: ${{ needs.build.outputs.script-file }}
    secrets:
      dummy-secret: ${{ secrets.DUMMY_SECRET }}

  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print result
        run: echo "${{ needs.deploy.outputs.result }}"

  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Something went wrong"
          echo ${{ toJSON(github) }}

  information:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Runs custom JS action
        uses: ./.github/actions/deploy-s3-javascript
