name: React CI Trigger

on:
  push:
    paths:
      - 'react-app-1/**'
  workflow_dispatch:

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Run React tests
        uses: ./react-app-1/.github/actions/test-project
        with:
          node-version: '24'
          working-directory: './react-app-1'

  deploy-project:
    needs: test-project
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Run dummy deploy
        uses: ./react-app-1/.github/actions/deploy
        with:
          working-directory: './react-app-1'
