name: Starting Project APP CI Trigger

env:
  APP_DIR: './starting-project'
  ARTIFACT_NAME: 'dist-files-starting-project'

on:
  push:
    branches:
      - main
    paths:
      - 'starting-project/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Run Test Action
        uses: ./starting-project/.github/actions/test
        with:
          working-directory: ${{ env.APP_DIR }}

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.build.outputs.script-file }}
    steps:
      - uses: actions/checkout@v5

      - name: Run Build Action
        id: build
        uses: ./starting-project/.github/actions/build
        with:
          working-directory: ${{ env.APP_DIR }}
          artifact-name: ${{ env.ARTIFACT_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Deploy Action
        uses: ./starting-project/.github/actions/deploy
        with:
          working-directory: ${{ env.APP_DIR }}
          artifact-name: ${{ env.ARTIFACT_NAME }}
          script-file: ${{ needs.build.outputs.script-file }}
